# Build stage
FROM node:alpine as build
WORKDIR /myapp
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run build

# production stage

FROM nginx:alpine
# COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /myapp/build /user/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]



