version: '3'


services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  backend:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=familytree
      - DB_USER=postgres
      - DB_PASSWORD=dev@iitj
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=familytree
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev@iitj
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:



# version: '3'

# services:
#   backend:
#     build:
#       context: ./django
#       dockerfile: Dockerfile
#     volumes:
#       - ./django:/app
#     env_file:
#       - .env
#     expose:
#       - "8000"

#   frontend:
#     build:
#       context: ./react
#       dockerfile: Dockerfile
#     expose:
#       - "80"

#   nginx:
#     build:
#       context: ./nginx
#     ports:
#       - "80:80"
#     depends_on:
#       - backend
#       - frontend
